name: Build and Deploy Website
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: src/Mock-Server/mock/api/v1/
        remote_path: /home/ubuntu/foo/
        remote_host: ec2-54-212-26-203.us-west-2.compute.amazonaws.com
        remote_port: 22
        remote_user: debian
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
   

    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
          node-version: '12.12.0'
    - name: yarn install and build
      run: |
        echo '"@k2:registry""https://npm.fury.io/${{ secrets.YARN_TOKEN }}/emumba"' > .yarnrc
        cat .yarnrc
        yarn -i
        yarn build
      working-directory: CRA-Example
      env:
        NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'CRA-Example/build'      # optional: defaults to entire repository
    - uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
