name: Build and Deploy Website
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Files
      uses: appleboy/scp-action@master
      env:
        HOST: "ec2-54-212-26-203.us-west-2.compute.amazonaws.com"
        USERNAME: "ubuntu"
        KEY: ${{ secrets.SSH_PRIVATE_KEY}}
      with:
        source: Mock-Server/mock/api/v1/
        target: "/home/ubuntu/foo/"
        strip_components: 1
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
          node-version: '12.12.0'
    - name: yarn install and build
      run: |
        echo '"@k2:registry""https://npm.fury.io/${{ secrets.YARN_TOKEN }}/emumba"' > .yarnrc
        cat .yarnrc
        yarn -i
        yarn build
      working-directory: CRA-Example
      env:
        NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'CRA-Example/build'      # optional: defaults to entire repository
    - uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
