name: Build and Deploy Website
on:
  push:
    branches:
    - ztna-demo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy Mock Files to EC2
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY}}
      with:
        source: Mock-Server/mock/
        target: "/home/ubuntu/projects/server/"
        strip_components: 1
    - uses: actions/setup-node@v1
      with:
          node-version: '12.12.0'
    - name: yarn install and build
      run: |
        echo -e " @k2:registry=https://registry.npmjs.org \n ${{ secrets.NPM_RC }} \n always-auth=true  \n" > .npmrc
        cat .npmrc
        yarn -i
        yarn build
      working-directory: CRA-Example
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'CRA-Example/build'      # optional: defaults to entire repository
    - uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
